// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7abY0_jPyEdDcREyzqvaFid6ZfOJzic',
    appId: '1:714721251820:android:1b6c9553bffe1988f670c9',
    messagingSenderId: '714721251820',
    projectId: 'criclivepro-88690',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirF22GqpmjdlrzEJl3oQm1R-155FKNdI',
    appId: '1:576622348248:ios:810278e72d0e5ba4a054ad',
    messagingSenderId: '944132584068',
    projectId: 'axcell-painting',
    databaseURL: 'https://axcell-painting-default-rtdb.firebaseio.com',
    storageBucket: 'findit-b7c5f.appspot.com',
    androidClientId: '944132584068-eh8e5mci4755p3b5r5egtolb1c3tkr3p.apps.googleusercontent.com',
    iosClientId: '944132584068-hmvgk084r5jab2ap7rtft2ehlv32k8og.apps.googleusercontent.com',
    iosBundleId: 'com.wm.axcell.axcellPainting',
  );
}
