import 'package:kisma_livescore/responses/live_score_response.dart';

final defaultPlayer = Players(
  csdId: 0,
  fullName: 'Unknown',
  nickName: 'Unknown',
  firstName: 'Unknown',
  lastName: 'Unknown',
  shortName: 'Unknown',
  isOnStrike: false,
  batsmanRuns: 0,
  balls: 0,
  fours: 0,
  sixes: 0,
  strikeRate: null,
  overs: 0.0,
  maidens: 0,
  wickets: 0,
  bowlerRuns: 0,
  economy: null,
  isCap: false,
  isWK: false,
  expBatOrder: 0,
  actBatOrder: 0,
  bowlOrder: 0,
  foursConc: 0,
  sixesConc: 0,
  dotBalls: 0,
  widesConc: 0,
  noBalls: 0,
  howOut: null,
  bowled: null,
  caught: null,
);